CREATE TABLE tramite (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nro VARCHAR(50) UNIQUE NOT NULL,
  asunto VARCHAR(255) NOT NULL,
  estado VARCHAR(30) NOT NULL,
  fecha DATETIME NOT NULL,
  solicitante VARCHAR(120)
);