
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

db.url=jdbc:mysql://localhost:3306/siga?useSSL=false&serverTimezone=UTC
db.user=dev_siga
db.password=dev_siga
db.pool.size=10

